### ISSUE TITLE
Cannot invoke "java.util.List.isEmpty()" because "strings" is null

### ISSUE THREAD

**Issue by wagulu** [open-obfuscator/dProtect#13]
Execution failed for task ':app:transformClassesAndResourcesWithProguardTransformForRelease'.
> Cannot invoke "java.util.List.isEmpty()" because "strings" is null

**Comment by hieunguyen-vkey** [comment]
Hi @wagulu,
Could you share how you resolve this issue? 
I'm getting this error.
Thanks
