### ISSUE TITLE
ProGuardTask missing from compiled distribution

### ISSUE THREAD

**Issue by v-p-b** [open-obfuscator/dProtect#9]
I followed the Compilation section on the website to create a release that includes some bugfixes missing from the beta release. I used the default properties included in the latest `main` of this repo. 

The distribution ZIP created with the `distZip` Gradle task includes `dprotect.jar`, that should include `proguard.gradle.ProGuardTask`, but the whole `proguard.gradle` package is missing from the JAR.

**Comment by romainthomas** [comment]
To have the plugin you need to create at ``fatJar``:

 ```bash
$ ./gradlew :dprotect:fatJar
```
